services:

  app:
    build: .
    ports:
      - 80:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: inventario
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql:9.0.1
    ports:
      - 3006:3006
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario
    volumes:
      - ./initdb/inventarioDump.sql:/docker-entrypoint-initdb.d/inventarioDump.sql